#!/bin/sh

# Gets album art, based on playerctl meta information.

TMPLOCATION=/tmp/albumart

url=$(playerctl metadata mpris:artUrl 2>/dev/null)
if [ -z "$url" ]; then
  exit 1
fi

wget -o /dev/null -q -O "${TMPLOCATION}.jpg" "$url"
convert "${TMPLOCATION}.jpg" "${TMPLOCATION}.png"
if [ ! -z "$WIDTH" ]; then
  if [ ! -z "$HEIGHT" ]; then
    convert "${TMPLOCATION}.jpg" -resize "${WIDTH}x${HEIGHT}" "${TMPLOCATION}.png"
  else
    convert "${TMPLOCATION}.jpg" "${TMPLOCATION}.png"
  fi
else
  convert "${TMPLOCATION}.jpg" "${TMPLOCATION}.png"
fi
