#!/bin/sh

res=$(rofi -p "> " -dmenu < ~/scripts/scrotmenu)

outfile="/home/mbell/Documents/scrots/auto/%Y-%m-%d_%H%M%S_scrot.png"

notify="notify-send 'scrot' 'Screenshot saved'"
if [ "$res" == "full scrot" ]; then
    cmd="scrot $outfile"
fi
if [ "$res" == "rectangular selection scrot" ]; then
    cmd="scrot -s $outfile"
fi
if [ "$res" == "scrot current window" ]; then
    cmd="scrot -b -u $outfile"
fi
if [ "$res" == "scrot (+5 seconds delay)" ]; then
    cmd="scrot -d 5 $outfile"
fi
if [ "$res" == "" ]; then
    exit
fi
sleep 1
eval $cmd && eval $notify
exit 0
