#!/bin/sh
# src: https://github.com/PatDan/dotfiles/blob/master/lemonbar/blocks/volume
# OLDCOLOR = 77777794A5BC  3E4958

CARD="${1:-0}"
MIXER="${2:-default}"
trap "echo Booh!" SIGHUP
if [ ! -z "$(whereis pamixer | grep -Po "(?<=:).*")" ]; then
  if [ "$(pamixer --get-mute)" == "true" ]; then
    mute="1"
  else
    mute="0"
  fi
else
  mute=$(amixer -c $CARD -M -D $MIXER get Master | grep Playback | grep -q off && echo 1 || echo 0)
fi

if [ $mute -eq 1 ]
then
	BAR="%{F#67727E}%{T4}%{T-}━━━━━━━━━━━━━━"
	pc="00"
	ICON=""
else
	# echo "━━━━━━━▊%{F#67727E}━━━━━━━"
	if [ ! -z "$(whereis pamixer | grep -Po "(?<=:).*")" ]; then
	  pc=$(pamixer --get-volume)
	else
	  pc=$(amixer -c $CARD -M -D $MIXER get Master |
	  echo $(sed -n "s/^[^:]*: Playback [0-9]* \[\([0-9]*%\)\] .*/$symbol \1/p" | head -n1))
	  pc=${pc::-1}
	fi
	if [ $pc -eq 100 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━━━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 91 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━━━━━━━%{F-}%{F#67727E}━%{F-}"
		ICON=""
	elif [ $pc -gt 83 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━━━━━━%{F-}%{F#67727E}━━%{F-}"
		ICON=""
	elif [ $pc -gt 75 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━━━━━%{F-}%{F#67727E}━━━%{F-}"
		ICON=""
	elif [ $pc -gt 67 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━━━━%{F-}%{F#67727E}━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 59 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━━━%{F-}%{F#67727E}━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 51 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━━%{F-}%{F#67727E}━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 43 ]
	then
		BAR="%{F#FFFFFF}━━━━━━━%{F-}%{F#67727E}━━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 35 ]
	then
		BAR="%{F#FFFFFF}━━━━━━%{F-}%{F#67727E}━━━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 27 ]
	then
		BAR="%{F#FFFFFF}━━━━━%{F-}%{F#67727E}━━━━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 19 ]
	then
		BAR="%{F#FFFFFF}━━━━%{F-}%{F#67727E}━━━━━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 11 ]
	then
		BAR="%{F#FFFFFF}━━━%{F-}%{F#67727E}━━━━━━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 3 ]
	then
		BAR="%{F#FFFFFF}━━%{F-}%{F#67727E}━━━━━━━━━━━━%{F-}"
		ICON=""
	elif [ $pc -gt 0 ]
	then
		BAR="%{F#FFFFFF}━%{F-}%{F#67727E}━━━━━━━━━━━━━%{F-}"
		ICON=""
	else
		BAR="%{F#67727E}━━━━━━━━━━━━━━%{F-}"
		ICON=""
	fi
fi

echo "$ICON $pc"








	

#amixer -c $CARD -M -D $MIXER get Master |
#echo $(sed -n "s/^[^:]*: Playback [0-9]* \[\([0-9]*%\)\] .*/$symbol \1/p" | head -n1)
#echo ""
#echo $(amixer -c $CARD -M -D $MIXER get Master | grep Playback | grep -q off && echo "#F5A3A3" || echo "#EEEEEE")
